Name Change dca to țarc
TuftsUniversity/tdl_on_hyrax pull request #57
Opened 2022-12-31 16:25 UTC by rawOrlando

@mkorcy lets put are work for this on the same branch so that we don't have to rebase when we are ready.

DCA changed their name to trac.

2023-01-13 20:51 UTC, mkorcy commented on app/models/datastreams/ead.rb
> -      # Since our old EADs have xmlns="http://dca.tufts.edu/schema/ead" and our new
This change isn't quite right.  The old EADs will continue to have dca.tufts.edu and the new ones as they say here will have something else.  They're not going to go back and update the old ones here (I talked to Adrienne about this) so this shouldn't get updated.

2023-01-13 20:52 UTC, mkorcy commented on spec/fixtures/MS226.archival.xml
> -<ead xmlns="http://dca.tufts.edu/schema/ead" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
For the same reason previously noted this wouldn't change.

2023-01-13 20:53 UTC, mkorcy commented on spec/fixtures/tufts_il.president.1824.xml
> -<aas:election_record xmlns:aas="http://dca.tufts.edu/aas" label="Illinois 1824 President of the United States" type="Legislative" iteration="First Ballot" date="1824-11" election_id="il.president.182
We don't know what we're going to do with AAS records yet.  We have a separate ticket on this.  This namespace change shouldn't happen right now.

2023-01-23 14:24 UTC, rawOrlando commented on app/models/datastreams/ead.rb
> -      # Since our old EADs have xmlns="http://dca.tufts.edu/schema/ead" and our new
@mkorcy I decided to split this stuff off into a separate PR. When I first decided on a big PR, I thought there would not be much of a feedback cycle. This will be split off so that there are changes. We know we have both looked it over and are happy with. #70

2023-01-26 21:30 UTC, mkorcy requested changes
Overall fine but I think the rebase here was weird?

2023-01-26 21:30 UTC, mkorcy commented on .env
> +SERVER_PORTS="4000:4000"
This file shouldn't be checked in, it should be in the .gitignore.

2023-01-26 21:30 UTC, mkorcy commented on .env
> +SERVER_PORTS="4000:4000"
Same for .DS_Store although I can't comment on that file.

2023-01-26 21:30 UTC, mkorcy commented on app/views/hyrax/voting_records/show.html.erb
> +      American Antiquarian Society and Tufts Archival Research Center, with funding from the
This change is in another PR it should be removed.

2023-01-26 21:30 UTC, mkorcy commented on docs/setup.md
> +# Setting up TDL on your computer
This was already in another PR?

2023-01-30 15:17 UTC, closed without merging