Change url from dca to tarc
TuftsUniversity/tdl_on_hyrax pull request #70
Opened 2023-01-23 14:22 UTC by rawOrlando

Splitting off this part of #57.
Will take care of https://tuftswork.atlassian.net/browse/TDLR-2454

2023-01-24 14:01 UTC, rawOrlando commented
Are we also changing `sites.tufts.edu/dca/`

2023-01-24 15:02 UTC, mkorcy requested changes
I requested a few minor changes, talked to Adrienne about the appropriate mapping for the http://dca.tufts.edu/ua/access/rights-pd.html URL in our fixtures, and the one I listed in comments is correct. And also, see my last note on the election fixture.

2023-01-25 20:20 UTC, rawOrlando commented on lib/tufts/populate_fixtures.rb
> +        rights_statement: "http://tarc.tufts.edu/ua/access/rights-pd.html",
Great! the old one also 404. But fixing that problem too!

2023-01-25 20:22 UTC, rawOrlando commented on spec/fixtures/tufts_il.president.1824.xml
> +<aas:election_record xmlns:aas="http://dca.tufts.edu/aas" label="Illinois 1824 President of the United States" type="Legislative" iteration="First Ballot" date="1824-11" election_id="il.president.182
Ok, I can get rid of this change. But do you want to keep the changes to the other fixtures? MS226, and MS999?

2023-01-26 15:09 UTC, mkorcy commented on spec/fixtures/tufts_il.president.1824.xml
> +<aas:election_record xmlns:aas="http://dca.tufts.edu/aas" label="Illinois 1824 President of the United States" type="Legislative" iteration="First Ballot" date="1824-11" election_id="il.president.182
Yeah, EAD fixtures I'm not worried about, they're going to go away soon anyway, but the NNV/AAS stuff is sticking around.

2023-01-26 21:24 UTC, mkorcy approved these changes
Good to go

2023-01-30 15:46 UTC, merged