Recaptcha
TuftsUniversity/tdl_on_hyrax pull request #97
Opened 2023-07-05 11:57 UTC by rawOrlando

tbd

2023-07-07 19:58 UTC, rawOrlando commented
I copied and app/controllers/hyrax/contact_form_controller.rb from hyrax to modify it slightly, should I also copy the spec for coveralls?

2023-07-11 20:41 UTC, mkorcy requested changes
2 small changes.  one for clarity on copying the file from hyrax locally just so i can keep track as we move towards hyrax 3/4 and just a request to delete a file we're not using anymore.

2023-07-11 20:41 UTC, mkorcy commented on app/controllers/hyrax/contact_form_controller.rb
> +# frozen_string_literal: true
for upgrade purposes can you add a note about why you copied this in to the source tree.

2023-07-17 12:27 UTC, rawOrlando commented on .travis.yml
What do you mean?

2023-07-17 18:14 UTC, mkorcy approved these changes
👍

2023-07-18 16:16 UTC, merged